### ISSUE TITLE
Configuration for use with SystemJS

### ISSUE THREAD

**Issue by mtrefzer** [yagajs/leaflet-ng2#219]
Hi,

I'm trying to use @yaga/leaflet-ng2 with SystemJs and struggling with the configuration.
These are my entries concerning @yaga/leaflet-ng2 in systemjs.config.js:
```
paths: {
    'npm:': 'node_modules/'
},
map: {
    ..........
    '@yaga/leaflet-ng2': 'npm:@yaga/leaflet-ng2/lib',
    ..........
},
packages: {
    ......
    '@yaga/leaflet-ng2': {
        main: './index.js',
        defaultExtension: 'js'
    },
    ......
}
```

but im getting this error and have no clue how to fix it:

```
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/leaflet
	Error: XHR error (404 Not Found) loading http://localhost:3000/leaflet
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3000/leaflet as "leaflet" from http://localhost:3000/node_modules/@yaga/leaflet-ng2/lib/index.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1230:39) [<root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3000/leaflet as "leaflet" from http://localhost:3000/node_modules/@yaga/leaflet-ng2/lib/index.js
```

**Comment by atd-schubert** [comment]
At the first look on the error, your configuration has a problem with leaflet.

`Error loading http://localhost:3000/leaflet as "leaflet"`.

This is just a guess from your configuratio. You have to add:

```js
{
    map: {
        // ..........
        'leaflet': 'npm:leaflet',
        // ..........
    },
    packages: {
        // ..........
        'leaflet': {
            main: './dist/leaflet-src.js',
                defaultExtension: 'js'
        }
        // ..........
    }
}
```

#### Or / And
Maybe you have some problems with your main configuration, but I don't really think so. You can try something like this:

```js
{
    map: {
        // ..........
        '@yaga/leaflet-ng2': 'npm:@yaga/leaflet-ng2', //<- remove lib
        // ..........
    },
    packages: {
        // ..........
        '@yaga/leaflet-ng2': {
            main: './lib/index.js', //<- add lib
                defaultExtension: 'js'
        }
        // ..........
    }
}
```

If it doesn't work, reply and I will take a deeper look at it again...

**Comment by mtrefzer** [comment]
Thanks mate, I didn't recognize the dependency on npm:leaflet so your  first sugested solution works.
That's my working configuration:

```
{
    paths: {
        'npm:': 'node_modules/'
    },
    map: {
        // ..........
        '@yaga/leaflet-ng2': 'npm:@yaga/leaflet-ng2/lib',
        'leaflet': 'npm:leaflet',
        // ..........
    },
    packages: {
        // ..........
        '@yaga/leaflet-ng2': {
            main: './index.js',
            defaultExtension: 'js'
        },
        'leaflet': {
            main: './dist/leaflet-src.js',
                defaultExtension: 'js'
        }
        // ..........
    }
}
```
